'use strict';

/**
 * @ngdoc function
 * @name youkaiwatchWhisperApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the youkaiwatchWhisperApp
 */
angular.module('youkaiwatchWhisperApp')
  .controller('MainCtrl', function ($scope) {
    $scope.awesomeThings = [
      'HTML5 Boilerplate',
      'AngularJS',
      'Karma'
    ];

    $scope.monsters = [
			{no: 1 ,name: "ぶようじん坊" ,rank: "E", place: "団々坂　機械の下",food: "おにぎり", etc: ""},
			{no: 2 ,name: "がらあきん坊" ,rank: "C", place: "おつかい横丁　あんのん団地",food: "おにぎり", etc: "【進化】ぶようじん防がLv.18で進化"},
			{no: 3 ,name: "さきがけの助" ,rank: "B", place: "団々坂　こひなた通り　機械の下（昼）",food: "おにぎり", etc: ""},
			{no: 4 ,name: "ダラケ刀" ,rank: "E", place: "おおもり山　廃トンネル　洞窟",food: "ジュース", etc: ""},
			{no: 5 ,name: "ザンバラ刀" ,rank: "E", place: "さくら中央シティ　工事現場",food: "ジュース", etc: "【進化】ダラケ刀がLv.20で進化"},
			{no: 6 ,name: "ダララだんびら" ,rank: "C", place: "さくら中央シティ　工事現場",food: "ジュース", etc: ""},
			{no: 7 ,name: "ちからモチ" ,rank: "D", place: "さくらニュータウン　魚屋の交差点　機械の下",food: "おにぎり", etc: ""},
			{no: 8 ,name: "やきモチ" ,rank: "D", place: "さくら中央シティ　さくらビジネスガーデンビル",food: "おにぎり", etc: ""},
			{no: 9 ,name: "カブトさん" ,rank: "D", place: "団々坂　おんぼろ屋敷",food: "野菜", etc: ""},
			{no: 10 ,name: "ゲンマ将軍" ,rank: "A", place: "妖魔界　あらくれ街道",food: "野菜", etc: "【合成】妖怪「カブトさん」と「ヨロイさん」"},
			{no: 11 ,name: "黄泉ゲンスイ" ,rank: "S", place: "団々坂　竹林のおんぼろ屋敷　離れ",food: "野菜", etc: "竹林のおんぼろ屋敷 離れ"},
			{no: 12 ,name: "メラメライオン" ,rank: "D", place: "さくら中央シティ　工事現場",food: "肉", etc: ""},
			{no: 13 ,name: "グラグライオン" ,rank: "B", place: "さくらチュータウン　さくら第一小学校　校舎（夜）",food: "肉", etc: ""},
			{no: 14 ,name: "轟獅子" ,rank: "Ａ", place: "さくらニュータウン　さくら第一小学校　茂みの中（夜雨）",food: "肉", etc: ""},
			{no: 15 ,name: "しょうブシ" ,rank: "C", place: "おつかい横丁　機械の下",food: "魚", etc: "サブクエストで友達になる"},
			{no: 16 ,name: "まさむね" ,rank: "A", place: "合成限定",food: "魚", etc: "【合成】妖怪「しょうブシ」と「名刀マサムネ」"},
			{no: 17 ,name: "むらまさ" ,rank: "A", place: "合成限定",food: "魚", etc: "【合成】妖怪「しょうブシ」と「名刀ムラマサ」"},
			{no: 18 ,name: "くさなぎ" ,rank: "S", place: "合成限定",food: "魚", etc: "【合成】妖怪「しょうぶし」と「神剣クサナギ」"},
			{no: 19 ,name: "ベンケイ" ,rank: "B", place: "そよ風ヒルズ　えびす台　機械の下",food: "料理", etc: ""},
			{no: 20 ,name: "からくりベンケイ" ,rank: "B", place: "そよ風ヒルズ　ひょうたん池博物館（夜）",food: "料理", etc: ""},
			{no: 21 ,name: "やまと" ,rank: "B", place: "おつかい横丁　たそがれ通り　機械の下",food: "おにぎり", etc: ""},
			{no: 22 ,name: "カブキ猿" ,rank: "A", place: "さくらチュータウン　さくら第一小学校　校舎（夜）",food: "おにぎり", etc: ""},
			{no: 23 ,name: "クワノ武士" ,rank: "B", place: "おおもり山　登山道　木の上（夜）",food: "野菜", etc: ""},
			{no: 24 ,name: "クワガ大将" ,rank: "S", place: "おおもり山　登山道　木の上",food: "野菜", etc: "【合成】妖怪「クワノ武士」と「大将の魂」"},
			{no: 25 ,name: "オオクワの神" ,rank: "S", place: "なし",food: "野菜", etc: "【妖怪ガシャ】スペシャルコインor赤コイン"},
			{no: 26 ,name: "くしゃ武者" ,rank: "S", place: "ムゲン地獄　第7階層",food: "肉", etc: "Sランクサブクエストで友達になる"},
			{no: 27 ,name: "なまはげ" ,rank: "S", place: "おつかい横丁　あんのん団地　空き部屋（夜）",food: "肉", etc: "赤信号を無視し続けると出現。"},
			{no: 28 ,name: "ズルズルづる" ,rank: "E", place: "団々坂　竹林のおんぼろ屋敷",food: "魚", etc: ""},
			{no: 29 ,name: "かぜカモ" ,rank: "D", place: "そよ風ヒルズ　西の川",food: "魚", etc: ""},
			{no: 30 ,name: "わすれん帽" ,rank: "E", place: "さくら中央シティ　木の上（夜）",food: "お菓子", etc: ""},
			{no: 31 ,name: "ばか頭巾" ,rank: "E", place: "さくら中央シティ　木の上（夜）",food: "お菓子", etc: ""},
			{no: 32 ,name: "つづかな僧" ,rank: "E", place: "団々坂　竹林のおんぼろ屋敷",food: "バーガー", etc: ""},
			{no: 33 ,name: "やめたい師" ,rank: "C", place: "団々坂　正天寺　お墓",food: "バーガー", etc: "【進化】】つづかな僧がLv.15で進化"},
			{no: 34 ,name: "もうせん和尚" ,rank: "C", place: "団々坂　あんのん団地　B-201",food: "バーガー", etc: ""},
			{no: 35 ,name: "わらえ姉" ,rank: "D", place: "団々坂　お団子台　木の上（昼）",food: "バーガー", etc: ""},
			{no: 36 ,name: "青くちびる" ,rank: "C", place: "団々坂　お団子台　木の上（夜）",food: "パン", etc: ""},
			{no: 37 ,name: "バクロ婆" ,rank: "D", place: "団々坂　竹林のおんぼろ屋敷",food: "ラーメン", etc: ""},
			{no: 38 ,name: "ババァーン" ,rank: "B", place: "なし",food: "ラーメン", etc: "【合成】】妖怪「バクロ婆」と「わらえ姉」"},
			{no: 39 ,name: "ドクロ婆" ,rank: "C", place: "おつかい横丁　かげむら医院 3階　車椅子（かげむら医院の外に出て建物の左側のツタから）",food: "ラーメン", etc: ""},
			{no: 40 ,name: "モテモ天" ,rank: "D", place: "さくら中央シティ　木の上",food: "パン", etc: ""},
			{no: 41 ,name: "モテマクール" ,rank: "A", place: "おつかい横丁　かげむら医院",food: "パン", etc: ""},
			{no: 42 ,name: "モテヌス" ,rank: "A", place: "さくら中央シティオフィス街　機械の下(夜)",food: "パン", etc: ""},
			{no: 43 ,name: "でんぱく小僧" ,rank: "D", place: "団々坂　電柱の上",food: "おにぎり", etc: ""},
			{no: 44 ,name: "でんじん" ,rank: "A", place: "ムゲン地獄",food: "おにぎり", etc: ""},
			{no: 45 ,name: "はつでんしん" ,rank: "S", place: "ムゲン地獄",food: "おにぎり", etc: ""},
			{no: 46 ,name: "うんがい鏡" ,rank: "C", place: "そよ風ヒルズ　木の上",food: "料理", etc: "メインクエスト中に友達になる"},
			{no: 47 ,name: "ヤミ鏡" ,rank: "A", place: "そよ風ヒルズ　木の上（夜）",food: "料理", etc: ""},
			{no: 48 ,name: "まぼ老師" ,rank: "C", place: "そよ風ヒルズ　機械の下",food: "料理", etc: ""},
			{no: 49 ,name: "かげ老師" ,rank: "C", place: "さくら中央シティ　工事現場",food: "料理", etc: ""},
			{no: 50 ,name: "ほう老師" ,rank: "B", place: "おつかい横丁　かげむら医院",food: "料理", etc: ""},
			{no: 51 ,name: "さとりちゃん" ,rank: "B", place: "そよ風ヒルズ　ひょうたん池博物館（夜）",food: "野菜", etc: ""},
			{no: 52 ,name: "よつめ" ,rank: "B", place: "さくらチュータウン　さくら第一小学校　校舎の中（夜）",food: "野菜", etc: ""},
			{no: 53 ,name: "天狗" ,rank: "S", place: "ストーリークリア後のサブクエスト",food: "お菓子", etc: "Sランクサブクエストで友達になる"},
			{no: 54 ,name: "ほむら天狗" ,rank: "S", place: "団々坂　月見峠　木の上(昼)",food: "お菓子", etc: ""},
			{no: 55 ,name: "キュウビ" ,rank: "S", place: "ストーリークリア後のサブエクスト",food: "魚", etc: "キュウビの入手方法"},
			{no: 56 ,name: "犬神" ,rank: "S", place: "",food: "魚", etc: "【妖怪ガシャ】スペシャルコインor黄色コイン"},
			{no: 57 ,name: "だるだるま" ,rank: "E", place: "さくらニュータウン　あちこちの機械の下",food: "パン", etc: ""},
			{no: 58 ,name: "だるまっちょ" ,rank: "B", place: "団々坂　こひなた駅前通り　機械の下",food: "パン", etc: "【合成】妖怪「だるだるま」と「ちからモチ」"},
			{no: 59 ,name: "ゴリだるま" ,rank: "B", place: "さくらニュータウン　さくら第一小学校　校舎の中（夜）",food: "パン", etc: ""},
			{no: 60 ,name: "ムリカベ" ,rank: "E", place: "さくらニュータウン　あちこちの茂みの中",food: "ラーメン", etc: ""},
			{no: 61 ,name: "むりだ城" ,rank: "A", place: "妖魔界",food: "ラーメン", etc: "【進化】ムリカベがLv.29で進化"},
			{no: 62 ,name: "シロカベ" ,rank: "A", place: "妖魔界",food: "ラーメン", etc: ""},
			{no: 63 ,name: "ヨロイさん" ,rank: "D", place: "団々坂　竹林のおんぼろ屋敷",food: "野菜", etc: ""},
			{no: 64 ,name: "モレゾウ" ,rank: "C", place: "さくらニュータウン　さくら第一小学校　茂みの中（昼）",food: "おにぎり", etc: ""},
			{no: 65 ,name: "ブルファント" ,rank: "C", place: "さくらニュータウン　さくら第一小学校　茂みの中（夜）",food: "おにぎり", etc: ""},
			{no: 66 ,name: "トオセンボン" ,rank: "D", place: "さくら中央シティ　工事現場（夜）",food: "牛乳", etc: ""},
			{no: 67 ,name: "くろがねセンボン" ,rank: "D", place: "桜町地下水道",food: "牛乳", etc: ""},
			{no: 68 ,name: "ふじのやま" ,rank: "C", place: "おおもり山　廃トンネル",food: "おにぎり", etc: ""},
			{no: 69 ,name: "さくらのじま" ,rank: "B", place: "そよ風ヒルズ　ひょうたん池博物館(夜)",food: "おにぎり", etc: ""},
			{no: 70 ,name: "グレるりん" ,rank: "E", place: "さくらニュータウン　ひとなし路地",food: "ラーメン", etc: ""},
			{no: 71 ,name: "ゴクドー" ,rank: "B", place: "そよ風ヒルズ　ひょうたん池博物館（夜）",food: "ラーメン", etc: ""},
			{no: 72 ,name: "アニ鬼" ,rank: "A", place: "そよ風ヒルズ　ひょうたん池　ボートの上",food: "ラーメン", etc: "妖怪レンズでウォッチをする"},
			{no: 73 ,name: "武者かぶと" ,rank: "B", place: "おおもり山　登山道　木の上(夜)",food: "野菜", etc: ""},
			{no: 74 ,name: "カブト無双" ,rank: "S", place: "さくらニュータウン 魚屋の交差点　木の上（夜）",food: "野菜", etc: ""},
			{no: 75 ,name: "オオツノノ神" ,rank: "S", place: "おおもり山　登山道（夜）",food: "野菜", etc: ""},
			{no: 76 ,name: "ドウカク" ,rank: "C", place: "さくら中央シティ　工事現場",food: "牛乳", etc: ""},
			{no: 77 ,name: "ギンカク" ,rank: "B", place: "さくら中央シティ　工事現場（夜）",food: "牛乳", etc: "【合成】】妖怪「ドウカク」「ドウカク」"},
			{no: 78 ,name: "キンカク" ,rank: "A", place: "",food: "牛乳", etc: "【合成】妖怪「ギンカク」「ギンカク」"},
			{no: 79 ,name: "プラチナカク" ,rank: "S", place: "そよ風ヒルズ　ひょうたん池公園　木の上(夜)",food: "牛乳", etc: "【合成】妖怪「キンカク」アイテム「プラチナゴット」"},
			{no: 80 ,name: "ロボニャン" ,rank: "A", place: "さくら中央シティ　工事現場3階　ゴミ置き場",food: "魚", etc: ""},
			{no: 81 ,name: "ゴルニャン" ,rank: "S", place: "",food: "魚", etc: "【妖怪ガシャ】スペシャルコインorオレンジコイン"},
			{no: 82 ,name: "だいぼらぼっち" ,rank: "S", place: "クリア後のサブクエスト",food: "野菜", etc: "Sランクサブクエストで友達になる"},
			{no: 83 ,name: "うみぼうず" ,rank: "S", place: "さくら中央シティ　さざなみ公園　海(雨)",food: "野菜", etc: ""},
			{no: 84 ,name: "しゃれこ婦人" ,rank: "E", place: "団々坂　こっそり空地",food: "バーガー", etc: ""},
			{no: 85 ,name: "カラカラさん" ,rank: "C", place: "そよ風ヒルズ　あちこち茂みの中",food: "バーガー", etc: "【合成】妖怪「しゃれこ婦人」と「モテモ天」"},
			{no: 86 ,name: "ほね美人" ,rank: "B", place: "そよ風ヒルズ　ひょうたん池博物館",food: "バーガー", etc: ""},
			{no: 87 ,name: "セミまる" ,rank: "E", place: "さくらニュータウン　木団々坂　木の上",food: "飲み物", etc: ""},
			{no: 88 ,name: "カゲまる" ,rank: "C", place: "そよ風ヒルズ　木の上",food: "ジュース", etc: "【進化】セミマルのLv.21を上げる"},
			{no: 89 ,name: "ヒグラシまる" ,rank: "B", place: "そよ風ヒルズ　ひょうたん池公園　木の上（昼）",food: "ジュース", etc: ""},
			{no: 90 ,name: "さむガリ" ,rank: "E", place: "おおもり山　どんこ池",food: "ラーメン", etc: ""},
			{no: 91 ,name: "ガリ王子" ,rank: "S", place: "おおもり山　どんこ池（昼）",food: "ラーメン", etc: "【合成】妖怪「さむガリ」とアイテム「雪王マント」"},
			{no: 92 ,name: "あつガルル" ,rank: "S", place: "ムゲン地獄　第7階層",food: "ラーメン", etc: ""},
			{no: 93 ,name: "ジャバニャン" ,rank: "D", place: "ムゲン地獄　第56階層",food: "魚", etc: "メインクエスト中"},
			{no: 94 ,name: "トゲニャン" ,rank: "B", place: "さくら中央シティ　オフィス街（昼）駐車場の動くスケボーをウォッチする。",food: "魚", etc: "【合成】妖怪「ジバニャン」と「イガイガグリ」"},
			{no: 95 ,name: "ワルニャン" ,rank: "B", place: "さくら中央シティ　オフィス街（夜）駐車場の動くスケボーをウォッチする。",food: "魚", etc: "【合成】妖怪「ジバニャン」と「グレるりん」"},
			{no: 96 ,name: "ノガッパ" ,rank: "D", place: "さくらニュータウン　西の川",food: "野菜", etc: ""},
			{no: 97 ,name: "たびガッパ" ,rank: "A", place: "団々坂　東の川おつかい横丁　かげむら医院",food: "野菜", etc: "【進化】ノガッパのLv.32を上げると進化"},
			{no: 98 ,name: "なみガッパ" ,rank: "A", place: "さくら中央シティ　海（昼）",food: "野菜", etc: ""},
			{no: 99 ,name: "コマさん" ,rank: "D", place: "ムゲン地獄",food: "牛乳", etc: ""},
			{no: 100 ,name: "ししコマ" ,rank: "A", place: "妖魔界　えっけん回廊",food: "牛乳", etc: ""},
			{no: 101 ,name: "コマじろう" ,rank: "D", place: "団々坂　おんぼろ屋敷",food: "牛乳", etc: ""},
			{no: 102 ,name: "とらじろう" ,rank: "A", place: "おつかい横丁　かげむら医院",food: "牛乳", etc: ""},
			{no: 103 ,name: "バク" ,rank: "D", place: "団々坂　竹やぶの道　竹やぶ",food: "ジュース", etc: ""},
			{no: 104 ,name: "ハク" ,rank: "C", place: "おつかい横丁　あんのん団地",food: "ジュース", etc: ""},
			{no: 105 ,name: "キュン太郎" ,rank: "C", place: "おおもり山　神社　茂みの中",food: "バーガー", etc: ""},
			{no: 106 ,name: "ズキュキュン太" ,rank: "B", place: "妖魔界　えっけん回廊",food: "バーガー", etc: "【合成】妖怪「キュン太郎」と「愛のシャク」"},
			{no: 107 ,name: "裏キュン太" ,rank: "A", place: "妖魔界　えっけん回廊",food: "バーガー", etc: ""},
			{no: 108 ,name: "ゆきおんな" ,rank: "B", place: "さくらニュータウン　さくら第一小学校　校舎（夜）",food: "お菓子", etc: ""},
			{no: 109 ,name: "ふぶき姫" ,rank: "S", place: "",food: "お菓子", etc: "【合成】妖怪「ゆきおんな」と「白銀のかみどめ」"},
			{no: 110 ,name: "百鬼姫" ,rank: "S", place: "",food: "お菓子", etc: "【妖怪ガシャ】スペシャルコインor桃コイン"},
			{no: 111 ,name: "ワカメくん" ,rank: "E", place: "さくら中央シティ　さざなみ公園　海",food: "ラーメン", etc: ""},
			{no: 112 ,name: "コンブさん" ,rank: "E", place: "さくら中央シティ　さざなみ公園　海（夜）",food: "ラーメン", etc: ""},
			{no: 113 ,name: "メカブちゃん" ,rank: "D", place: "さくら中央シティ　さざなみ公園　海",food: "ラーメン", etc: ""},
			{no: 114 ,name: "うらやましろう" ,rank: "E", place: "団々坂　こっそり空地",food: "ラーメン", etc: ""},
			{no: 115 ,name: "つまみぐいのすけ" ,rank: "D", place: "おつかい横丁　茂みの中",food: "ラーメン", etc: ""},
			{no: 116 ,name: "ひも爺" ,rank: "E", place: "さくらニュータウン　怪しい路地裏　ゴミ置き場",food: "おにぎり", etc: ""},
			{no: 117 ,name: "くいい爺" ,rank: "B", place: "さくらニュータウン　怪しい路地裏　ゴミ置き場",food: "おにぎり", etc: ""},
			{no: 118 ,name: "こめ爺" ,rank: "B", place: "妖魔界",food: "おにぎり", etc: "ウォッチロックＳを進んだ場所"},
			{no: 119 ,name: "びんボーイ" ,rank: "D", place: "さくら中央シティ　塾への近道　ゴミ捨て場(夜)",food: "牛乳", etc: ""},
			{no: 120 ,name: "らくてん童" ,rank: "C", place: "さくら中央シティ　塾への近道 ゴミ捨て場(昼)",food: "牛乳", etc: ""},
			{no: 121 ,name: "ぜっこう蝶" ,rank: "D", place: "おおもり山　木の上（昼）",food: "ジュース", etc: ""},
			{no: 122 ,name: "ゼッコウ蝶" ,rank: "D", place: "おおもり山　木の上（夜）",food: "シュース", etc: ""},
			{no: 123 ,name: "サイコウ蝶" ,rank: "A", place: "おつかい横丁　かげむら医院",food: "ジュース", etc: "【合成】妖怪「ぜっこう蝶」と「ゼッコウ蝶」"},
			{no: 124 ,name: "アゲアゲハ" ,rank: "S", place: "おおもり山　登山道",food: "ジュース", etc: ""},
			{no: 125 ,name: "ホノボーノ" ,rank: "C", place: "さくら中央シティ　学生通り　木の上",food: "パン", etc: ""},
			{no: 126 ,name: "ヒョウヘンヌ" ,rank: "A", place: "妖魔界　うそつき山",food: "パン", etc: "【合成】妖怪「ドンヨリーヌ」と「ノホホーン」"},
			{no: 127 ,name: "ヒョウヘンナ" ,rank: "A", place: "妖魔界　うそつき山",food: "パン", etc: ""},
			{no: 128 ,name: "サンタク老師" ,rank: "B", place: "さくらニュータウン　さんかく通り　木の上(夜)",food: "牛乳", etc: ""},
			{no: 129 ,name: "ふくろじい" ,rank: "B", place: "さくらニュータウン　さくら第一小学校　校舎（夜）",food: "牛乳", etc: ""},
			{no: 130 ,name: "さいの目入道" ,rank: "A", place: "妖魔界",food: "お菓子", etc: ""},
			{no: 131 ,name: "ゾロ目大明神" ,rank: "A", place: "そよ風ヒルズ　機械の下",food: "お菓子", etc: ""},
			{no: 132 ,name: "雷オトン" ,rank: "A", place: "団々坂　お団子台　電柱の上（夜）",food: "肉", etc: ""},
			{no: 133 ,name: "絶オジイ" ,rank: "S", place: "団々坂　お団子台　電柱の上（雨夜）",food: "肉", etc: ""},
			{no: 134 ,name: "聖オカン" ,rank: "S", place: "ムゲン地獄　第3階層",food: "野菜", etc: ""},
			{no: 135 ,name: "心オバア" ,rank: "S", place: "",food: "野菜", etc: "【妖怪ガシャャ】スペシャルコインor緑コイン"},
			{no: 136 ,name: "みちび鬼" ,rank: "E", place: "さくらニュータウン　あちこちの茂みの中",food: "お菓子", etc: ""},
			{no: 137 ,name: "えこひい鬼" ,rank: "D", place: "さくら中央シティ　ゆきおんなの裏道",food: "お菓子", etc: ""},
			{no: 138 ,name: "かたのり小僧" ,rank: "E", place: "団々坂　おんぼろ屋敷",food: "お菓子", etc: ""},
			{no: 139 ,name: "かたのり親方" ,rank: "C", place: "団々坂　廃トンネル　東の洞窟",food: "お菓子", etc: "【合成】妖怪「かたのり小僧」と「親方ダンベル」"},
			{no: 140 ,name: "ぎっくり男" ,rank: "B", place: "団々坂　廃トンネル",food: "お菓子", etc: ""},
			{no: 141 ,name: "ネガティブーン" ,rank: "E", place: "さくらニュータウン　木の上さくらニュータウン　路地裏",food: "ジュース", etc: ""},
			{no: 142 ,name: "ジャネガブーン" ,rank: "C", place: "さくらニュータウン　木の上",food: "ジュース", etc: "【進化】ネガティブーンがレベルで進化"},
			{no: 143 ,name: "かゆかゆ" ,rank: "A", place: "さくらニュータウン　木の上（雨）",food: "ジュース", etc: ""},
			{no: 144 ,name: "ジミー" ,rank: "E", place: "さくらニュータウン",food: "おにぎり", etc: ""},
			{no: 145 ,name: "カゲロー" ,rank: "B", place: "よそ風ヒルズ　もののけ道",food: "おにぎり", etc: "【進化】ジミーのレベルを上げると進化"},
			{no: 146 ,name: "カイム" ,rank: "A", place: "おつかい横丁　かげむら医院",food: "おにぎり", etc: ""},
			{no: 147 ,name: "ヒキコウモリ" ,rank: "D", place: "おおもり山　廃トンネル",food: "肉", etc: ""},
			{no: 148 ,name: "ドジコウモリウ" ,rank: "A", place: "妖魔界　うそつき山",food: "肉", etc: "【合成】妖怪「ヒキコウモリ」と「ネクラマテング」"},
			{no: 149 ,name: "ヤドコウモリ" ,rank: "A", place: "妖魔界　あらくれ街道",food: "肉", etc: ""},
			{no: 150 ,name: "ぎしんあん鬼" ,rank: "D", place: "さくらニュータウン",food: "料理", etc: ""},
			{no: 152 ,name: "あまのじゃく" ,rank: "B", place: "そよ風ヒルズ　ひょうたん池博物館（夜）",food: "料理", etc: ""},
			{no: 153 ,name: "ネクラマテング" ,rank: "C", place: "おつかい横丁　あんのん団地　木の上（夜）",food: "野菜", etc: ""},
			{no: 154 ,name: "ヨミテング" ,rank: "B", place: "おつかい横丁　あんのん団地　木の上（昼）",food: "野菜", etc: ""},
			{no: 155 ,name: "魔ガサス" ,rank: "A", place: "おつかい横丁　たそがれ通り　木の上（昼）",food: "野菜", etc: "【妖怪ガシャ】わくわくコイン"},
			{no: 156 ,name: "ウ魔" ,rank: "A", place: "おつかい横丁　こかげ通り　木の上（夜）",food: "野菜", etc: ""},
			{no: 157 ,name: "デビビル" ,rank: "A", place: "妖魔界　街道",food: "ラーメン", etc: ""},
			{no: 158 ,name: "デビビラン" ,rank: "S", place: "さくら中央シティ　学生通り　車のした（昼）",food: "ラーメン", etc: "【合成】妖怪「デビビル」と「邪心のかたまり」"},
			{no: 159 ,name: "虫歯男爵" ,rank: "S", place: "妖怪ガシャ（スペシャルコイン）",food: "ラーメン", etc: ""},
			{no: 160 ,name: "ドケチング" ,rank: "S", place: "ムゲン地獄",food: "肉", etc: ""},
			{no: 161 ,name: "ヤミまろ" ,rank: "S", place: "桜町地下水道　ボス",food: "肉", etc: "桜町地下下水道"},
			{no: 162 ,name: "イガイガグリ" ,rank: "E", place: "さくらニュータウン　木の上",food: "パン", etc: ""},
			{no: 163 ,name: "チクチクウニ" ,rank: "D", place: "桜町地下水道　水の中",food: "パン", etc: ""},
			{no: 164 ,name: "ヨコドリ" ,rank: "E", place: "おおもり山　茂みの中",food: "バーガー", etc: ""},
			{no: 165 ,name: "はらおドリ" ,rank: "D", place: "さくら中央シティ　さくらビジネスガーデンビル",food: "バーガー", etc: ""},
			{no: 166 ,name: "トホホギス" ,rank: "E", place: "おおもり山　木の上",food: "パン", etc: ""},
			{no: 167 ,name: "ブカッコウ" ,rank: "C", place: "おつかい横丁　木の上",food: "パン", etc: ""},
			{no: 168 ,name: "死神鳥" ,rank: "A", place: "団々坂　鳥飼家　隠し部屋",food: "パン", etc: "鳥飼さんのサブクエストを進める"},
			{no: 169 ,name: "じんめん犬" ,rank: "E", place: "団々坂　こっそり空き地　ゴミ置き場ムゲン地獄",food: "料理", etc: ""},
			{no: 170 ,name: "かおベロス" ,rank: "B", place: "さくらニュータウン　さくら第一小学校　校舎の中（夜）",food: "料理", etc: "【合成】妖怪「じんめん犬」と「じんめん犬」"},
			{no: 171 ,name: "三途の犬" ,rank: "A", place: "妖魔界",food: "料理", etc: ""},
			{no: 172 ,name: "じめりんぼう" ,rank: "E", place: "さくらニュータウン　さびしげな水路",food: "ジュース", etc: ""},
			{no: 173 ,name: "雨ふらし" ,rank: "B", place: "桜町地下水道　水の中",food: "ジュース", etc: ""},
			{no: 174 ,name: "こおりんぼう" ,rank: "E", place: "桜町地下水道",food: "ジュース", etc: ""},
			{no: 175 ,name: "化けあられ" ,rank: "B", place: "桜町地下水道",food: "ジュース", etc: ""},
			{no: 176 ,name: "たらりん" ,rank: "D", place: "桜町地下水道 （そよ風ヒルズ付近）",food: "ジュース", etc: ""},
			{no: 177 ,name: "口だけおんな" ,rank: "D", place: "さくら中央シティ　さくらビジネスガーデンビル",food: "パン", etc: "サブクエストで友達になれる"},
			{no: 178 ,name: "おつぼね様" ,rank: "Ｃ", place: "さくら中央シティ　オフィス街　機械の下（昼）",food: "パン", etc: ""},
			{no: 179 ,name: "ドンヨリーヌ" ,rank: "D", place: "さくら中央シティ　塾への近道　ゴミ置き場",food: "パン", etc: "メインクエスト中に友達になれる"},
			{no: 180 ,name: "ならず者" ,rank: "C", place: "おつかい横丁　商店街の細道",food: "牛乳", etc: ""},
			{no: 181 ,name: "へこ鬼神" ,rank: "A", place: "おつかい横丁　かげむら医院",food: "牛乳", etc: ""},
			{no: 182 ,name: "おすべり様" ,rank: "A", place: "おつかい横丁　かげむら医院",food: "お菓子", etc: ""},
			{no: 183 ,name: "おしっしょう" ,rank: "A", place: "妖魔界",food: "お菓子", etc: ""},
			{no: 184 ,name: "しわくちゃん" ,rank: "B", place: "そよ風ヒルズ　えびす台　茂みの中",food: "牛乳", etc: ""},
			{no: 185 ,name: "老いらん" ,rank: "S", place: "",food: "牛乳", etc: "【合成】妖怪「しわくちゃん」と「生命のおしろい」"},
			{no: 186 ,name: "ふじみ御前" ,rank: "S", place: "",food: "牛乳", etc: "【妖怪ガシャ】スペシャルコインor紫コイン"},
			{no: 187 ,name: "フゥミン" ,rank: "S", place: "ムゲン地獄",food: "お菓子", etc: ""},
			{no: 188 ,name: "おねむの精" ,rank: "S", place: "ムゲン地獄",food: "お菓子", etc: ""},
			{no: 189 ,name: "ツチノコ" ,rank: "E", place: "団々坂　ひみつの抜け道",food: "バーガー", etc: ""},
			{no: 190 ,name: "フクリュウ" ,rank: "A", place: "ムゲン地獄",food: "バーガー", etc: "【合成】妖怪「ツチノコ」と「幸福のしずく」"},
			{no: 191 ,name: "ツチノコパンダ" ,rank: "A", place: "すれちがい通信",food: "バーガー", etc: "すれちがい通信の「さすらい荘」"},
			{no: 192 ,name: "笑ウツボ" ,rank: "D", place: "おおもり山　どんこ池（昼）",food: "肉", etc: ""},
			{no: 193 ,name: "歌ウナギ" ,rank: "C", place: "おおもり山　どんこ池（夜）",food: "肉", etc: ""},
			{no: 194 ,name: "大蛇のツボ" ,rank: "C", place: "団々坂　ひがん山トンネル　川（夜）",food: "肉", etc: ""},
			{no: 195 ,name: "キライギョ" ,rank: "D", place: "さくら中央シティ　西の川",food: "肉", etc: ""},
			{no: 196 ,name: "ゾウオ" ,rank: "B", place: "さくら中央シティ　西の川",food: "肉", etc: ""},
			{no: 197 ,name: "ギャクジョウウオ" ,rank: "A", place: "おつかい横丁　東の川（夜）",food: "肉", etc: ""},
			{no: 198 ,name: "りゅーくん" ,rank: "D", place: "ムゲン地獄　3階4階",food: "料理", etc: "メインクエスト中に友達になる"},
			{no: 199 ,name: "龍神" ,rank: "S", place: "団々坂　竹やぶの道　竹やぶ(昼)",food: "料理", etc: "【合成】「りゅーくん」と「龍神玉」"},
			{no: 200 ,name: "青龍" ,rank: "S", place: "ムゲン地獄 第4階層",food: "料理", etc: ""},
			{no: 201 ,name: "ボー防" ,rank: "C", place: "おつかい横丁　たそがれ通り　茂みの中（昼）",food: "お菓子", etc: "【妖怪ガシャ】わくわくコインン"},
			{no: 202 ,name: "しどろもどろ" ,rank: "B", place: "おつかい横丁　こかげ通り　茂みの中",food: "お菓子", etc: ""},
			{no: 203 ,name: "ミチクササメ" ,rank: "C", place: "桜街地下水道",food: "野菜", etc: ""},
			{no: 204 ,name: "トーシロザメ" ,rank: "B", place: "そよ風ヒルズ　もののけ道",food: "野菜", etc: ""},
			{no: 205 ,name: "ムダヅカイ" ,rank: "C", place: "よそ風ヒルズ　西の川",food: "パン", etc: ""},
			{no: 206 ,name: "はらわシェル" ,rank: "B", place: "そよ風ヒルズ　西の川（夜）",food: "パン", etc: "おおもり山　神社の「お賽銭」で出現"},
			{no: 207 ,name: "ナガハナ" ,rank: "C", place: "おつかい横丁　あんのん団地　空き部屋",food: "お菓子", etc: ""},
			{no: 208 ,name: "ナガバナナ" ,rank: "A", place: "おつかい横丁　あんのん団地　空き部屋",food: "お菓子", etc: ""},
			{no: 209 ,name: "しきるん蛇" ,rank: "B", place: "さくらニュータウン　さくら第一小学校　校舎（夜）",food: "魚", etc: ""},
			{no: 210 ,name: "すねスネーク" ,rank: "B", place: "サンライズ通り　茂みの中",food: "魚", etc: ""},
			{no: 211 ,name: "まむし行司" ,rank: "A", place: "妖魔界",food: "魚", etc: ""},
			{no: 212 ,name: "オロチ" ,rank: "S", place: "メインクエスト",food: "魚", etc: "メインクエスト中に倒すと友達になる"},
			{no: 213 ,name: "影オロチ" ,rank: "S", place: "",food: "魚", etc: "【妖怪ガシャ】スペシャルコインor水色コイン"},
			{no: 214 ,name: "ブシニャン" ,rank: "S", place: "【レジェンド妖怪について】",food: "", etc: ""},
			{no: 215 ,name: "しゅらコマ" ,rank: "S", place: "【レジェンド妖怪について】",food: "", etc: ""},
			{no: 216 ,name: "イケメン犬" ,rank: "S", place: "【レジェンド妖怪について】",food: "", etc: ""},
			{no: 217 ,name: "花さか爺" ,rank: "S", place: "【レジェンド妖怪について】",food: "", etc: ""},
			{no: 218 ,name: "山吹鬼" ,rank: "S", place: "【レジェンド妖怪について】",food: "", etc: ""},
			{no: 219 ,name: "サファイニャン" ,rank: "A", place: "【宝石系ジバニャンについて】",food: "", etc: "QRコード"},
			{no: 220 ,name: "エメラルニャン" ,rank: "A", place: "【宝石系ジバニャンについて】",food: "", etc: "QRコード"},
			{no: 221 ,name: "ルビーニャン" ,rank: "A", place: "【宝石系ジバニャンについて】",food: "", etc: "QRコード"},
			{no: 222 ,name: "トパニャン" ,rank: "A", place: "【宝石系ジバニャンについて】",food: "", etc: "QRコード"},
			{no: 223 ,name: "ダイヤニャン" ,rank: "A", place: "【宝石系ジバニャンについて】",food: "", etc: "QRコード"}
    ];
  });
